"""Generate only sampling-UI glyphs and the supplied Lab3 Anlogic mark.
No font dependency or readmem path is needed by the synthesized design.
"""
from pathlib import Path
import hashlib,json,re
from PIL import Image,ImageDraw,ImageFont
project=Path(__file__).resolve().parent.parent
repo=project.parents[1];workspace=repo.parent
hdl=project/'user_source/hdl_source';assets=project/'sim/osd_assets';assets.mkdir(exist_ok=True)
font_cjk=Path('C:/Windows/Fonts/msyh.ttc');font_ascii=Path('C:/Windows/Fonts/consola.ttf')
logo_src=workspace/'7_lab_ex_2026_nosoft/lab_hd_3_osd/lab_hd_3_osd/user_source/hdl_source/anlogic_logo_rom.v'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert sha(logo_src)=='37c76680345f17a85632b7835e46a3a197cf75fdd91ca6a970b75f5346e7a9f8'
labels=['曝光','增益','半行','档号','最近采样','未标定','等待采样','有件','空穴','配置中','无输入','等待有效帧','采样有效','累计异常']
chars=''.join(dict.fromkeys(''.join(labels)));ids={ch:i+1 for i,ch in enumerate(chars)}
ascii_chars=''.join(sorted(set(' ANLOGICEXPGIMNFRCSTUYDVHW0123456789ABCDEF-+')))
def bitmap(ch,size,path,fontsize):
 im=Image.new('L',size);d=ImageDraw.Draw(im);font=ImageFont.truetype(str(path),fontsize)
 box=d.textbbox((0,0),ch,font=font)
 d.text(((size[0]-(box[2]-box[0]))//2-box[0],(size[1]-(box[3]-box[1]))//2-box[1]),ch,font=font,fill=255)
 return im.point(lambda p:255 if p>=100 else 0)
def rom(name,width,depth,values):
 assert len(values)==depth
 addr=(depth-1).bit_length();hexwidth=(width+3)//4
 text=f'// Generated by sim/generate_osd_assets.py; synchronous initialized ROM.\nmodule {name}(input wire clk,input wire [{addr-1}:0] address,output reg [{width-1}:0] data);\nreg [{width-1}:0] memory [0:{depth-1}];\ninitial begin\n'
 text+=''.join(f" memory[{i}]={width}'h{value:0{hexwidth}x};\n" for i,value in enumerate(values))
 text+='end\nalways @(posedge clk) data<=memory[address];\nendmodule\n'
 (hdl/(name+'.v')).write_text(text,encoding='ascii')
 (assets/(name+'.hex')).write_text(''.join(f'{v:0{hexwidth}x}\n' for v in values),encoding='ascii')
av=[0]*2048
for ch in ascii_chars:
 im=bitmap(ch,(8,16),font_ascii,14)
 for y in range(16):av[ord(ch)*16+y]=sum((im.getpixel((x,y))!=0)<<(7-x) for x in range(8))
rom('osd_ascii_rom',8,len(av),av)
depth=1<<((len(chars)+1)*32-1).bit_length();cv=[0]*depth
for ch,idx in ids.items():
 im=bitmap(ch,(24,24),font_cjk,23)
 for y in range(24):cv[idx*32+y]=sum((im.getpixel((x,y))!=0)<<(23-x) for x in range(24))
rom('osd_cjk_rom',24,len(cv),cv)
mark=Image.new('RGB',(160,160),'white')
for address,value in re.findall(r"15'd(\d+)\s*:\s*O_pixel\s*=\s*25'h([0-9a-fA-F]+)",logo_src.read_text()):
 a=int(address);v=int(value,16)
 if v>>24:mark.putpixel((a%160,a//160),((v>>16)&255,(v>>8)&255,v&255))
mark=mark.crop((7,34,153,128)).resize((96,62),Image.Resampling.LANCZOS)
logo=Image.new('RGB',(96,64),'white');logo.paste(mark,(0,1));lv=[0]*8192
palette=[(255,255,255),(32,70,134),(204,37,59)]
for y in range(64):
 for x in range(96):
  rgb=logo.getpixel((x,y));idx=min(range(3),key=lambda i:sum((rgb[j]-palette[i][j])**2 for j in range(3)))
  lv[y*128+x]=idx;logo.putpixel((x,y),palette[idx])
rom('osd_logo_rom',2,len(lv),lv);logo.save(assets/'logo.png')
atlas=Image.new('RGB',(12*32,((len(chars)+11)//12)*40),'#142336');d=ImageDraw.Draw(atlas)
for i,ch in enumerate(chars):
 im=bitmap(ch,(24,24),font_cjk,23);atlas.paste('white',((i%12)*32,(i//12)*40),im)
 d.text(((i%12)*32,(i//12)*40+25),str(ids[ch]),fill='white')
atlas.save(assets/'cjk_atlas.png')
meta={'cjk_glyph_ids':ids,'ascii_chars':ascii_chars,'sources':{str(f):sha(f) for f in [font_cjk,font_ascii,logo_src]},
      'rom_bits':{'ascii':len(av)*8,'cjk':len(cv)*24,'logo':len(lv)*2},
      'generated_sha256':{name:sha(hdl/name) for name in ['osd_ascii_rom.v','osd_cjk_rom.v','osd_logo_rom.v']}}
(assets/'manifest.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
# Fixed layout decoded into glyph + row/column, then synchronous ROM and compose.
blocks=[]
def field(x,y,text,kind='ascii',scale=1,color="24'hffffff",dynamic=None):
 w=8 if kind=='ascii' else 24;ht=16 if kind=='ascii' else 24
 size=len(text);condition=f'x>={x} && x<{x+size*w*scale} && y>={y} && y<{y+ht*scale}'
 rows=[f' if({condition}) begin',f'  glyph_cjk={1 if kind=="cjk" else 0};ink_color={color};',
       f'  glyph_row=(y-{y})/{scale};']
 for i,ch in enumerate(text):
  expr=dynamic[i] if dynamic else (f"7'd{ord(ch)}" if kind=='ascii' else f"6'd{ids[ch]}")
  rows.append(f'  if(x>={x+i*w*scale} && x<{x+(i+1)*w*scale}) begin glyph={expr};glyph_col=(x-{x+i*w*scale})/{scale};end')
 rows+=[' end']
 blocks.append('\n'.join(rows))
field(128,24,'ANLOGIC',scale=2)
field(360,8,'曝光',kind='cjk');field(424,8,'EXP',scale=2)
field(360,40,'     ',scale=2,dynamic=[f'decimal(exp_bcd,{i})' for i in range(5)])
field(456,44,'半行',kind='cjk')
field(688,8,'增益',kind='cjk');field(752,8,'GAIN',scale=2)
field(688,40,'     ',scale=2,dynamic=[f'decimal(gain_bcd,{i})' for i in range(5)])
field(784,44,'档号',kind='cjk')
field(864,8,'MODE',scale=2,color="24'hb0c0d4")
field(864,40,' '*9,scale=2,dynamic=[f'mode_glyph(mode_s,{i})' for i in range(9)])
field(16,510,'最近采样',kind='cjk',color="24'hb0c0d4")
state_words=['未标定','等待采样','有件','空穴']
dynamic=["result_glyph(class_s,%d)"%i for i in range(4)]
field(16,540,'    ',kind='cjk',scale=2,color='result_color',dynamic=dynamic)
for label,x,val in [('MEAN',304,'mean_bcd'),('MIN',464,'min_bcd'),('MAX',624,'max_bcd')]:
 field(x,510,label,scale=2,color="24'hb0c0d4")
 field(x+80 if label=='MEAN' else x+64,510,'   ',scale=2,dynamic=[f"sample_s ? decimal({val},{i+2}) : 7'd45" for i in range(3)])
field(768,514,'采样有效',kind='cjk',color="24'h74dbc7",dynamic=[f"sample_s ? 6'd{ids[ch]} : 6'd0" for ch in '采样有效'])
diag=[]
def literal(t):diag.extend(f"7'd{ord(c)}" for c in t)
def dec(v):diag.extend(f'decimal({v},{i})' for i in range(5))
def hexes(v,n):diag.extend(f'hexchar({v}[{(n-i-1)*4}+:4])' for i in range(n))
literal('IN ');dec('w_bcd');literal('X');dec('h_bcd');literal(' FPS ');dec('fps_bcd');literal(' CFG ');diag.append("cfg_s ? 7'd49 : 7'd48")
for label,v in [(' L ','lane_s'),(' F ','format_s'),(' I ','i2c_s'),(' G ','gap_s')]:literal(label);hexes(v,4)
literal(' HEX');assert len(diag)*8<=704
field(304,548,' '*len(diag),dynamic=diag)
diag=[];literal('EC ')
diag.extend(f"edge_sample_s ? hexchar(edge_count_s[{(3-i)*4}+:4]) : 7'd45" for i in range(4))
literal(' GS ')
diag.extend(f"edge_sample_s ? hexchar(edge_sum_s[{(5-i)*4}+:4]) : 7'd45" for i in range(6))
literal(' T 80')
field(808,548,' '*len(diag),color="24'hffae64",dynamic=diag)
diag=[];literal('FR ');hexes('frames_s',8);literal(' SEC ');hexes('uptime_s',8);literal(' HEX')
field(304,576,' '*len(diag),dynamic=diag)
reasons=['配置中','无输入','等待有效帧','采样有效']
field(624,572,'     ',kind='cjk',color="reason_s==1 ? 24'hef7186 : 24'hb0c0d4",dynamic=[f'reason_glyph(reason_s,{i})' for i in range(5)])
field(920,572,'累计异常',kind='cjk',color="24'hf7b955",dynamic=[f"error_s ? 6'd{ids[ch]} : 6'd0" for ch in '累计异常'])
for xpos,label,value in [(536,'OF ','overflow_s'),(752,'VF ','lost_s'),(832,'UF ','underflow_s')]:
 diag=[];literal(label);hexes(value,4)
 field(xpos,576,' '*len(diag),color="24'hffae64",dynamic=diag)

# Previous AWB epoch: rejection bits, minimum input row period, max credit wait.
diag=["7'd69","7'd82","7'd32","hexchar(diagnostics_s[35:32])","7'd32","7'd76","7'd80","7'd32"]
diag += [f"hexchar(diagnostics_s[{shift}+:4])" for shift in [28,24,20,16]]
diag += ["7'd32","7'd87","7'd83","7'd32"]
diag += [f"hexchar(diagnostics_s[{shift}+:4])" for shift in [12,8,4,0]]
field(128,56,' '*len(diag),color="24'hffae64",dynamic=diag)

def glyph_func(name,words,bits):
 s=f'function [5:0] {name};\n input [{bits-1}:0] code;input [2:0] position;\n begin\n  {name}=0;\n  case(code)\n'
 for code,word in enumerate(words):
  s+=f'   {code}: case(position)\n'+''.join(f"    {i}: {name}=6'd{ids[ch]};\n" for i,ch in enumerate(word))+f'    default: {name}=0;\n   endcase\n'
 return s+'  endcase\n end\nendfunction\n'
base='''// Sampling UI. Three pixel clocks for RGB, DE, HS, VS and ENABLE bypass.
module experiment_osd #(
 parameter ENABLE=1,ROI_X0=256,ROI_X1=768,ROI_Y0=172,ROI_Y1=428,
 parameter SAMPLE_X0=472,SAMPLE_X1=552,SAMPLE_Y0=260,SAMPLE_Y1=340
)(
 input wire clk,rst_n,vs,hs,de,input wire [23:0] rgb,
 input wire [15:0] exposure,gain,
 input wire [1:0] view_mode,input wire [12:0] edge_count,input wire [23:0] edge_sum,
 input wire roi_valid,input wire [7:0] roi_mean,roi_min,roi_max,input wire [1:0] roi_state,
 input wire [15:0] width,height,fps,lane_errors,format_errors,i2c_errors,gaps,
 input wire [31:0] frames,uptime,input wire cfg_done,
 input wire [15:0] overflow_frames,lost_frames,underflow_frames,
 input wire [35:0] diagnostics,
 output reg out_vs,out_hs,out_de,output reg [23:0] out_rgb
);
reg vs_d,de_d;reg [10:0] x;reg [9:0] y;
wire start=vs && !vs_d;
wire [19:0] exp_bcd,gain_bcd,mean_bcd,min_bcd,max_bcd,w_bcd,h_bcd,fps_bcd;
bin16_bcd b0(clk,rst_n,start,exposure,exp_bcd);
bin16_bcd b1(clk,rst_n,start,gain,gain_bcd);
bin16_bcd b2(clk,rst_n,start,{8'd0,roi_mean},mean_bcd);
bin16_bcd b3(clk,rst_n,start,{8'd0,roi_min},min_bcd);
bin16_bcd b4(clk,rst_n,start,{8'd0,roi_max},max_bcd);
bin16_bcd b5(clk,rst_n,start,width,w_bcd);
bin16_bcd b6(clk,rst_n,start,height,h_bcd);
bin16_bcd b7(clk,rst_n,start,fps,fps_bcd);
reg [15:0] lane_s,format_s,i2c_s,gap_s,overflow_s,lost_s,underflow_s;
reg [31:0] frames_s,uptime_s;
reg [35:0] diagnostics_s;
reg sample_s,cfg_s,error_s,edge_sample_s;reg [1:0] class_s,reason_s,mode_s;
reg [15:0] edge_count_s;reg [23:0] edge_sum_s;
always @(posedge clk or negedge rst_n) begin
 if(!rst_n) begin
  vs_d<=0;de_d<=0;x<=0;y<=0;sample_s<=0;cfg_s<=0;error_s<=0;
  overflow_s<=0;lost_s<=0;underflow_s<=0;diagnostics_s<=0;
  mode_s<=0;edge_sample_s<=0;edge_count_s<=0;edge_sum_s<=0;
  class_s<=1;reason_s<=0;lane_s<=0;format_s<=0;i2c_s<=0;gap_s<=0;frames_s<=0;uptime_s<=0;
 end else begin
  vs_d<=vs;de_d<=de;
  if(vs) begin x<=0;y<=0;end
  else if(de) x<=x+1'b1;
  else if(de_d) begin x<=0;y<=y+1'b1;end
  if(start) begin
   overflow_s<=overflow_frames;lost_s<=lost_frames;underflow_s<=underflow_frames;diagnostics_s<=diagnostics;
   mode_s<=view_mode;edge_count_s<={3'd0,edge_count};edge_sum_s<=edge_sum;
   edge_sample_s<=roi_valid && cfg_done && fps!=0 && view_mode[1];
   sample_s<=roi_valid && cfg_done && fps!=0;
   class_s<=!cfg_done || fps==0 || !roi_valid ? 2'd1 : roi_state;
   reason_s<=!cfg_done ? 2'd0 : fps==0 ? 2'd1 : !roi_valid ? 2'd2 : 2'd3;
   lane_s<=lane_errors;format_s<=format_errors;i2c_s<=i2c_errors;gap_s<=gaps;
   frames_s<=frames;uptime_s<=uptime;cfg_s<=cfg_done;
   error_s<=|lane_errors || |format_errors || |i2c_errors || |gaps;
  end
 end
end
function [6:0] decimal;
 input [19:0] value;input [2:0] position;
 reg [3:0] nibble;reg blank;
 begin
  case(position)
   0: begin nibble=value[19:16];blank=value[19:16]==0;end
   1: begin nibble=value[15:12];blank=value[19:12]==0;end
   2: begin nibble=value[11:8];blank=value[19:8]==0;end
   3: begin nibble=value[7:4];blank=value[19:4]==0;end
   default: begin nibble=value[3:0];blank=0;end
  endcase
  decimal=blank ? 7'd32 : 7'd48+nibble;
 end
endfunction
function [6:0] hexchar;
 input [3:0] value;begin hexchar=value<10 ? 7'd48+value : 7'd55+value;end
endfunction
'''
base+=glyph_func('result_glyph',state_words,2)+glyph_func('reason_glyph',reasons,2)
base+='function [6:0] mode_glyph;\n input [1:0] code;input [3:0] position;\n begin\n mode_glyph=7\'d32;\n case(code)\n'
for code,word in enumerate(['RAW','GRAY','EDGE','GRAY+EDGE']):
 base+=f' {code}: case(position)\n'+''.join(f" {i}: mode_glyph=7'd{ord(ch)};\n" for i,ch in enumerate(word))+" default: mode_glyph=7'd32;\n endcase\n"
base+=' endcase\n end\nendfunction\n'
base+='''wire [23:0] result_color=class_s==0 ? 24'hf7b955 : class_s==2 ? 24'h74dbc7 : class_s==3 ? 24'hffae64 : 24'hb0c0d4;
reg [6:0] glyph;reg glyph_cjk;reg [4:0] glyph_col,glyph_row;reg [23:0] ink_color;
always @* begin
 glyph=0;glyph_cjk=0;glyph_col=0;glyph_row=0;ink_color=24'hffffff;
'''+ '\n'.join(blocks)+'''\nend
wire roi_inside=x>=ROI_X0 && x<ROI_X1 && y>=ROI_Y0 && y<ROI_Y1;
wire roi_border=roi_inside && (x==ROI_X0 || x==ROI_X1-1 || y==ROI_Y0 || y==ROI_Y1-1);
wire sample_inside=x>=SAMPLE_X0 && x<SAMPLE_X1 && y>=SAMPLE_Y0 && y<SAMPLE_Y1;
wire sample_border=sample_inside && (x==SAMPLE_X0 || x==SAMPLE_X1-1 || y==SAMPLE_Y0 || y==SAMPLE_Y1-1);
wire [9:0] gray_sum={2'd0,rgb[23:16]}+{1'd0,rgb[15:8],1'b0}+{2'd0,rgb[7:0]};
wire [7:0] gray=gray_sum[9:2];
wire [23:0] picture=ENABLE && sample_border ? 24'h00ffff :
 ENABLE && roi_border ? 24'h00ff40 : rgb;
reg [10:0] ascii_address;
reg [10:0] cjk_address;
reg [12:0] logo_address;
wire [5:0] logo_y=y-10'd8;
wire [6:0] logo_x=x-11'd16;
wire [7:0] ascii_row;wire [23:0] cjk_row;wire [1:0] logo_pixel;
osd_ascii_rom u_ascii(clk,ascii_address,ascii_row);
osd_cjk_rom u_cjk(clk,cjk_address,cjk_row);
osd_logo_rom u_logo(clk,logo_address,logo_pixel);
reg [1:0] hs_p,vs_p,de_p,panel_p,logo_p,cjk_p;
reg [4:0] col0,col1;
reg [23:0] rgb0,rgb1,ink0,ink1;
wire ink=cjk_p[1] ? (col1<24 && cjk_row[23-col1]) : (col1<8 && ascii_row[7-col1]);
always @(posedge clk or negedge rst_n) begin
 if(!rst_n) begin
  ascii_address<=0;cjk_address<=0;logo_address<=0;
  hs_p<=0;vs_p<=0;de_p<=0;panel_p<=0;logo_p<=0;cjk_p<=0;
  col0<=0;col1<=0;rgb0<=0;rgb1<=0;ink0<=0;ink1<=0;
  out_vs<=0;out_hs<=0;out_de<=0;out_rgb<=0;
 end else begin
  ascii_address<={glyph,glyph_row[3:0]};
  cjk_address<={glyph[5:0],glyph_row};
  logo_address<={logo_y,logo_x};
  hs_p<={hs_p[0],hs};vs_p<={vs_p[0],vs};de_p<={de_p[0],de};
  panel_p<={panel_p[0],(de && (y<80 || y>=504))};
  logo_p<={logo_p[0],(x>=16 && x<112 && y>=8 && y<72)};
  cjk_p<={cjk_p[0],glyph_cjk};col0<=glyph_col;col1<=col0;
  rgb0<=picture;rgb1<=rgb0;ink0<=ink_color;ink1<=ink0;
  out_vs<=vs_p[1];out_hs<=hs_p[1];out_de<=de_p[1];
  out_rgb<=ENABLE && panel_p[1] ?
   (logo_p[1] ? (logo_pixel==1 ? 24'h204686 : logo_pixel==2 ? 24'hcc253b : 24'hffffff) :
    ink ? ink1 : 24'h142336) : rgb1;
 end
end
endmodule
'''
(hdl/'experiment_osd.v').write_text(base,encoding='ascii')
print('Generated',len(chars),'CJK glyphs,',len(ascii_chars),'ASCII glyphs; ROM bits',meta['rom_bits'])
