def run(_context):
    c,o=component('P01_对称托臂',65)
    box(c,'Arm_flat',-12,-80,'support_z-soft_t-pad_t-10 mm',24,190,10)
    box(c,'Wide_root',-26,100,'support_z-soft_t-pad_t-40 mm',52,10,50,OP.JoinFeatureOperation)
    for x in [-12,8]:
        triangle(c,'Under_rib_'+str(x),'x',x,4,100,'support_z-soft_t-pad_t-10 mm',-95,-30,OP.JoinFeatureOperation)
    slots(c,'Pad_position_slots','z','support_z-soft_t-pad_t-11 mm',12,[(0,-49),(0,49)],60)
    slots(c,'Root_fine_slots','y',99,12,[(-18,'support_z-soft_t-pad_t-10 mm'),(18,'support_z-soft_t-pad_t-10 mm')],'camera_slot_l')
    instance(c,-65)
    wall=next(o.component for o in D.rootComponent.occurrences if o.component.name.startswith('W02'))
    holes(wall,'Lowest_camera_row','y','wall_y-1 mm','wood_t+2 mm',[(x,125) for x in [-83,-47,47,83]])
    c,o=component('P02_加宽四点承托块',65)
    box(c,'Support_pad','-pad_w/2','board_w/2-support_depth','support_z-soft_t-pad_t','pad_w','pad_depth','pad_t')
    holes(c,'Through_fasteners','z','support_z-soft_t-pad_t-1 mm','pad_t+2 mm',[(0,'board_w/2+9 mm'),(0,'board_w/2+21 mm')])
    instance(c,-65);instance(c,65,rotation=math.pi);instance(c,-65,rotation=math.pi)
    c,o=component('S01_承托软垫_现场裁切',65)
    box(c,'Contact_soft_pad','-pad_w/2','board_w/2-support_depth','support_z-soft_t','pad_w','support_depth','soft_t')
    instance(c,-65);instance(c,65,rotation=math.pi);instance(c,-65,rotation=math.pi)
    report('camera_arms_and_supports')
