def run(_context):
    c,o=component('E01_传送带机身_已知包络')
    box(c,'Machine_envelope','-belt_l/2','-machine_w/2',0,'belt_l','machine_w','machine_h-2 mm')
    c,o=component('E02_带面_高度暂定')
    box(c,'Belt_surface','-belt_l/2','-belt_w/2','belt_z-2 mm','belt_l','belt_w',2)
    c,o=component('E03_下亚克力_厚度暂定')
    box(c,'Lower_acrylic','-lens_dx-board_l/2','-lens_dy-board_w/2','support_z','board_l','board_w','acrylic_lower_t')
    c,o=component('E04_板卡及器件_包络非内部设计')
    box(c,'PCB_and_components_envelope','-lens_dx-board_l/2','-lens_dy-board_w/2','support_z+acrylic_lower_t+2 mm','board_l','board_w','stack_h-acrylic_lower_t-acrylic_upper_t-4 mm')
    c,o=component('E05_上亚克力_厚度暂定')
    box(c,'Upper_acrylic','-lens_dx-board_l/2','-lens_dy-board_w/2','support_z+stack_h-acrylic_upper_t','board_l','board_w','acrylic_upper_t')
    c,o=component('E06_镜头_实际突出量待测')
    cylinder(c,'Lens','z','lens_z','lens_body_h',0,0,'lens_d')
    c,o=component('E07_摄像头座_暂定避让包络')
    box(c,'Camera_mount_envelope',-12,-12,'lens_z+lens_body_h',24,24,'lens_drop-lens_body_h')
    c,o=component('E08_环形灯_90x40x22')
    cylinder(c,'Ring_light','z','lamp_bottom','lamp_h',0,'lamp_y','lamp_od',inner='lamp_id')
    report('equipment_reference_envelopes')
